services:  
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8000:80"
    environment:
        - POSTGRES=postgres
    develop:
      watch:
        - path: src
          action: rebuild
        - path: requirements
          action: rebuild
        - path: docker/api
          action: rebuild
  postgres:
    image: "postgres:17.4-bookworm"
    ports:
        - "7432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=resultes