services:  
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:80"
    environment:
        - POSTGRES=postgres
  postgres:
    image: "postgres:17.4-bookworm"
    ports:
        - "7432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=resultes