apiVersion: apps/v1
kind: Deployment
metadata:
  name: server

  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/match-tag: true

spec:
  replicas: 1
  selector:
    matchLabels:
      resultes.net/component: server
  template:
    metadata:
      labels:
        resultes.net/component: server
    spec:
      containers:
        - image: ghcr.io/resultes-net/server:latest
          name: server
          env:
            - name: POSTGRES_PASSWORD
              value: example
            - name: PORT
              value: "80"
            - name: DB_HOST_NAME
              value: server-db.server.svc.cluster.local
            - name: ROOT_PATH
              value: /api

          ports:
            - containerPort: 80
              protocol: TCP
      imagePullSecrets:
        - name: read-ghcr-io-auth-secret
      restartPolicy: Always
