apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-server

  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/match-tag: true

spec:
  replicas: 1
  selector:
    matchLabels:
      resultes.net/component: external-server
  template:
    metadata:
      labels:
        resultes.net/component: external-server
    spec:
      containers:
        - image: ghcr.io/resultes-net/server:latest
          name: external-server
          args: ["external_server.py"]
          env:
            - name: POSTGRES_PASSWORD
              value: example
            - name: PORT
              value: "80"
            - name: DB_HOST_NAME
              value: server-db.server.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: ROOT_PATH
              value: /api
          volumeMounts:
            - name: secrets-volume
              mountPath: /app/config/secrets
              readOnly: true
          ports:
            - containerPort: 80
              protocol: TCP
      volumes:
        - name: secrets-volume
          secret:
            secretName: swift
      initContainers:
        - image: ghcr.io/resultes-net/server-migrate:latest
          name: migrate
          env:
            - name: POSTGRES_PASSWORD
              value: example
            - name: DB_HOST_NAME
              value: server-db.server.svc.cluster.local
            - name: DB_PORT
              value: "5432"

      imagePullSecrets:
        - name: read-ghcr-io-auth-secret
      restartPolicy: Always
