"""Add simulation name.

Revision ID: 0aa753691930
Revises: 146768374931
Create Date: 2026-01-26 17:05:43.766566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '0aa753691930'
down_revision: Union[str, None] = '146768374931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True))
    op.execute("UPDATE simulation set name = ''")
    op.alter_column('simulation', 'name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulation', 'name')
    # ### end Alembic commands ###
