"""Add error states.

Revision ID: 146768374931
Revises: 14dcf5ec14ff
Create Date: 2026-01-26 14:27:40.902847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '146768374931'
down_revision: Union[str, None] = '14dcf5ec14ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='variationstate',
        new_values=['WAITING', 'RUNNING', 'DONE', 'ERROR'],
        affected_columns=[TableReference(table_schema='public', table_name='variation', column_name='state')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='simulationstate',
        new_values=['WAITING_FOR_VARIATIONS_CREATION', 'CREATING_VARIATIONS', 'WAITING_FOR_VARIATION_RUNS', 'RUNNING_VARIATIONS', 'WAITING_FOR_CROSS_VARIATION_PROCESSING', 'CROSS_PROCESSING_VARIATIONS', 'DONE', 'ERROR'],
        affected_columns=[TableReference(table_schema='public', table_name='simulation', column_name='state')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='simulationstate',
        new_values=['WAITING_FOR_VARIATIONS_CREATION', 'CREATING_VARIATIONS', 'WAITING_FOR_VARIATION_RUNS', 'RUNNING_VARIATIONS', 'WAITING_FOR_CROSS_VARIATION_PROCESSING', 'CROSS_PROCESSING_VARIATIONS', 'DONE'],
        affected_columns=[TableReference(table_schema='public', table_name='simulation', column_name='state')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='variationstate',
        new_values=['WAITING', 'RUNNING', 'DONE'],
        affected_columns=[TableReference(table_schema='public', table_name='variation', column_name='state')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
