"""Add intermediate simulation states.

Revision ID: 14ced35ad641
Revises: 86428c02e057
Create Date: 2025-06-10 15:55:47.258754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '14ced35ad641'
down_revision: Union[str, None] = '86428c02e057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='simulationstate',
        new_values=['WAITING_FOR_VARIATIONS_CREATION', 'CREATING_VARIATIONS', 'WAITING_FOR_VARIATION_RUNS', 'RUNNING_VARIATIONS', 'WAITING_FOR_CROSS_VARIATION_PROCESSING', 'CROSS_PROCESSING_VARIATIONS', 'DONE'],
        affected_columns=[TableReference(table_schema='public', table_name='simulation', column_name='state')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='simulationstate',
        new_values=['WAITING_FOR_VARIATIONS_CREATION', 'WAITING_FOR_VARIATION_RUNS', 'WAITING_FOR_CROSS_VARIATION_PROCESSING', 'DONE'],
        affected_columns=[TableReference(table_schema='public', table_name='simulation', column_name='state')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
