"""Add ports to PTES storage parameters.

Revision ID: 14dcf5ec14ff
Revises: 7db9a82dda48
Create Date: 2026-01-05 13:02:55.556554

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

import copy
import sqlalchemy.orm as orm
import sqlalchemy.orm.session as sess


# revision identifiers, used by Alembic.
revision: str = "14dcf5ec14ff"
down_revision: Union[str, None] = "7db9a82dda48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

Base = orm.declarative_base()


class Simulation(Base):
    __tablename__ = "simulation"

    id = sa.Column(sa.String, primary_key=True, nullable=False)
    parameters = sa.Column(sa.JSON)


ports = {
    "values": {
        "storage": {
            "ports_relative_heights_1": {"top": 0.95, "middle": 0.50, "bottom": 0.05}
        }
    }
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    statement = sa.select(Simulation).where(
        Simulation.parameters[("values", "type")].as_string() == "ptes"
    )

    with sess.Session(bind=op.get_bind()) as session:
        simulations = session.scalars(statement)

        for simulation in simulations:
            parameters = copy.deepcopy(simulation.parameters)
            parameters["values"]["storage"]["ports_relative_heights_1"] = {
                "top": 0.95,
                "middle": 0.50,
                "bottom": 0.05,
            }

            simulation.parameters = parameters

        session.commit()

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    statement = sa.select(Simulation).where(
        Simulation.parameters[("values", "type")].as_string() == "ptes"
    )

    with sess.Session(bind=op.get_bind()) as session:

        simulations = session.scalars(statement)

        for simulation in simulations:
            parameters = copy.deepcopy(simulation.parameters)
            del parameters["values"]["storage"]["ports_relative_heights_1"]

            simulation.parameters = parameters

        session.commit()

    # ### end Alembic commands ###
