"""Remove `unique` field from foreign keys.

Revision ID: 3f121540fa11
Revises: c888f409c6c6
Create Date: 2025-05-15 16:31:55.153582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

import resultes_server


# revision identifiers, used by Alembic.
revision: str = '3f121540fa11'
down_revision: Union[str, None] = 'c888f409c6c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('simulation_user_id_key', 'simulation', type_='unique')
    op.drop_constraint('variation_simulation_id_key', 'variation', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('variation_simulation_id_key', 'variation', ['simulation_id'])
    op.create_unique_constraint('simulation_user_id_key', 'simulation', ['user_id'])
    # ### end Alembic commands ###
