"""Initial schema.

Revision ID: 4b2544451d66
Revises: 
Create Date: 2026-07-25 00:53:30.191987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b2544451d66'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('TTES', 'PTES', 'BTES', name='type').create(op.get_bind())
    op.create_table('latestlogin',
    sa.Column('on', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('on')
    )
    op.create_table('user',
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation',
    sa.Column('state', postgresql.ENUM('WAITING_FOR_VARIATIONS_CREATION', 'CREATING_VARIATIONS', 'WAITING_FOR_VARIATION_RUNS', 'RUNNING_VARIATIONS', 'WAITING_FOR_CROSS_VARIATION_PROCESSING', 'CROSS_PROCESSING_VARIATIONS', 'DONE', 'ERROR', name='simulationstate', create_type=False), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('location', postgresql.ENUM('BERLIN', 'BRUSSELS', 'COPENHAGEN', 'MADRID', 'ZURICH', name='location', create_type=False), nullable=False),
    sa.Column('type', postgresql.ENUM('TTES', 'PTES', 'BTES', name='type', create_type=False), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state_changed_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parameters',
    sa.Column('simulation_id', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('parameters', postgresql.JSONB, nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation.id'], ),
    sa.PrimaryKeyConstraint('simulation_id')
    )
    op.create_table('variation',
    sa.Column('state', postgresql.ENUM('WAITING', 'RUNNING', 'DONE', 'ERROR', name='variationstate', create_type=False), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('state_changed_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('relative_deck_file_containing_dir_path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variation')
    op.drop_table('parameters')
    op.drop_table('simulation')
    op.drop_table('user')
    op.drop_table('latestlogin')
    sa.Enum('TTES', 'PTES', 'BTES', name='type').drop(op.get_bind())
    # ### end Alembic commands ###
