"""Add `state_changed_on` to `Variation`.

Revision ID: 518bd4cea91e
Revises: 683aa74b166d
Create Date: 2025-08-06 13:16:35.402284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel





# revision identifiers, used by Alembic.
revision: str = '518bd4cea91e'
down_revision: Union[str, None] = '683aa74b166d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    import datetime as dt

    default_iso_formatted = '2025-08-06T11:19:37.644562+00:00'
    default = dt.datetime.fromisoformat(default_iso_formatted)

    op.add_column('variation', sa.Column('state_changed_on', sa.DateTime(timezone=True), nullable=True))
    
    variation = sa.table('variation', sa.column('state_changed_on'))
    op.execute(variation.update().values(state_changed_on=default))
    
    op.alter_column('variation', 'state_changed_on', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variation', 'state_changed_on')
    # ### end Alembic commands ###
