"""Remove uneeded fields from `Variation`.

Revision ID: 683aa74b166d
Revises: 14ced35ad641
Create Date: 2025-07-15 10:20:41.727757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '683aa74b166d'
down_revision: Union[str, None] = '14ced35ad641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variation', 'object_storage_url')
    op.drop_column('variation', 'relative_process_script_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variation', sa.Column('relative_process_script_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.add_column('variation', sa.Column('object_storage_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
