"""Initial migration.

Revision ID: 8acd094ab086
Revises: 
Create Date: 2025-05-03 17:11:26.495123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8acd094ab086'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('simulation',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('TTES', 'PTES', 'BTES', name='type'), nullable=False),
    sa.Column('parameters', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('object_storage_url', resultes_server.database_utils.helpers.TypeDecorator(length=2048), nullable=False),
    sa.Column('state', sa.Enum('WAITING_FOR_VARIATION_CREATION', 'WAITING_FOR_VARIATION_RUNS', 'WAITING_FOR_CROSS_VARIATION_PROCESSING', 'DONE', name='state'), nullable=False),
    sa.Column('state_changed_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('variation',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('simulation_id', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('object_storage_url', resultes_server.database_utils.helpers.TypeDecorator(length=2048), nullable=False),
    sa.Column('relative_deck_file_path', resultes_server.database_utils.helpers.TypeDecorator(length=2048), nullable=False),
    sa.Column('relative_process_script_path', resultes_server.database_utils.helpers.TypeDecorator(length=2048), nullable=False),
    sa.Column('state', sa.Enum('WAITING', 'RUNNING', 'DONE', name='state'), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('simulation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variation')
    op.drop_table('simulation')
    op.drop_table('user')
    # ### end Alembic commands ###
