"""Add `progress` column to `simulation` and `variation`.

Revision ID: 91167972f2fe
Revises: 20a1334235ac
Create Date: 2025-12-12 16:40:42.635133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '91167972f2fe'
down_revision: Union[str, None] = '20a1334235ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation', sa.Column('progress', sa.Integer(), nullable=False))
    op.add_column('variation', sa.Column('progress', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variation', 'progress')
    op.drop_column('simulation', 'progress')
    # ### end Alembic commands ###
