"""Rename `relative_deck_file_path` to `relative_deck_file_containing_dir_path`.

Revision ID: 97b22ee41e73
Revises: 518bd4cea91e
Create Date: 2025-08-08 14:05:02.589224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '97b22ee41e73'
down_revision: Union[str, None] = '518bd4cea91e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('variation', 'relative_deck_file_path', new_column_name='relative_deck_file_containing_dir_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('variation', 'relative_deck_file_containing_dir_path', new_column_name='relative_deck_file_path')
    # ### end Alembic commands ###
