"""Pull up pydantic models from DB models.

Revision ID: 9b7809d4c5e7
Revises: 3f121540fa11
Create Date: 2025-05-22 11:23:04.182223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b7809d4c5e7'
down_revision: Union[str, None] = '3f121540fa11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulation', 'type')
    sa.Enum('TTES', 'PTES', 'BTES', name='type').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('TTES', 'PTES', 'BTES', name='type').create(op.get_bind())
    op.add_column('simulation', sa.Column('type', postgresql.ENUM('TTES', 'PTES', 'BTES', name='type', create_type=False), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
