"""Create parameters table after previous attempt failed.

Revision ID: ba210e8eaaba
Revises: a380bca31f2c
Create Date: 2026-07-25 00:27:17.234997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

import sqlalchemy.dialects.postgresql as postgresql



# revision identifiers, used by Alembic.
revision: str = 'ba210e8eaaba'
down_revision: Union[str, None] = 'a380bca31f2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parameters', sa.Column('simulation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('parameters', sa.Column('parameters', postgresql.JSONB, nullable=False))
    op.create_foreign_key(None, 'parameters', 'simulation', ['simulation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError()
