"""Initial commit.

Revision ID: c888f409c6c6
Revises: 
Create Date: 2025-05-15 14:19:41.278287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

import database_utils
import type_decorators

# revision identifiers, used by Alembic.
revision: str = 'c888f409c6c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('WAITING_FOR_VARIATIONS_CREATION', 'WAITING_FOR_VARIATION_RUNS', 'WAITING_FOR_CROSS_VARIATION_PROCESSING', 'DONE', name='simulationstate').create(op.get_bind())
    sa.Enum('TTES', 'PTES', 'BTES', name='type').create(op.get_bind())
    sa.Enum('WAITING', 'RUNNING', 'DONE', name='variationstate').create(op.get_bind())
    op.create_table('user',
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('simulation',
    sa.Column('type', postgresql.ENUM('TTES', 'PTES', 'BTES', name='type', create_type=False), nullable=False),
    sa.Column('parameters', type_decorators.PydanticJsonTypeDecorator(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('object_storage_url', database_utils.helpers.NullableHttpUrlTypeDecorator(length=1024), nullable=True),
    sa.Column('state', postgresql.ENUM('WAITING_FOR_VARIATIONS_CREATION', 'WAITING_FOR_VARIATION_RUNS', 'WAITING_FOR_CROSS_VARIATION_PROCESSING', 'DONE', name='simulationstate', create_type=False), nullable=False),
    sa.Column('state_changed_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('variation',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('simulation_id', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('object_storage_url', database_utils.helpers.NullableHttpUrlTypeDecorator(length=1024), nullable=True),
    sa.Column('relative_deck_file_path', database_utils.helpers.PureWindowsPathTypeDecorator(length=1024), nullable=False),
    sa.Column('relative_process_script_path', database_utils.helpers.PureWindowsPathTypeDecorator(length=1024), nullable=False),
    sa.Column('state', postgresql.ENUM('WAITING', 'RUNNING', 'DONE', name='variationstate', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('simulation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variation')
    op.drop_table('simulation')
    op.drop_table('user')
    sa.Enum('WAITING', 'RUNNING', 'DONE', name='variationstate').drop(op.get_bind())
    sa.Enum('TTES', 'PTES', 'BTES', name='type').drop(op.get_bind())
    sa.Enum('WAITING_FOR_VARIATIONS_CREATION', 'WAITING_FOR_VARIATION_RUNS', 'WAITING_FOR_CROSS_VARIATION_PROCESSING', 'DONE', name='simulationstate').drop(op.get_bind())
    # ### end Alembic commands ###
