"""Add ISO weather data sets.

Revision ID: e2de16a7a23b
Revises: 4b2544451d66
Create Date: 2026-09-22 23:50:45.162054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'e2de16a7a23b'
down_revision: Union[str, None] = '4b2544451d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='location',
        new_values=['BERLIN', 'BRUSSELS', 'COPENHAGEN', 'MADRID', 'ZURICH', 'ALPINE', 'COLD', 'DRY', 'HOT', 'MEDITERRANEAN', 'SUBTROPIC', 'TEMPERATE', 'TROPICAL', 'WET'],
        affected_columns=[TableReference(table_schema='public', table_name='simulation', column_name='location')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='location',
        new_values=['BERLIN', 'BRUSSELS', 'COPENHAGEN', 'MADRID', 'ZURICH'],
        affected_columns=[TableReference(table_schema='public', table_name='simulation', column_name='location')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
