apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-db
spec:
  replicas: 1
  selector:
    matchLabels:
      resultes.net/component: server-db
  template:
    metadata:
      labels:
        resultes.net/component: server-db
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-auth-secret
                  key: password
            - name: ROOT_PATH
            - name: POSTGRES_DB
              value: resultes
          image: postgres
          name: server-db
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: db-persistent-volume
              mountPath: /var/lib/postgresql
      restartPolicy: Always
      volumes:
      - name: db-persistent-volume
        persistentVolumeClaim:
          claimName: db-persistent-volume-claim
