name: Create and publish Docker images

on:
  push:
    branches:
      - '*'

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.RESULTES_DOCKER_UTILS_APP }}
          private-key: ${{ secrets.RESULTES_DOCKER_UTILS_APP_KEY }}
          repositories: |
            resultes-server
            resultes-docker-utils
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false
          submodules: 'true'
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -f docker/api/Dockerfile -t ghcr.io/spf-ost/resultes-server-api:latest .

      - name: Push Docker image
        id: push
        run: |
          $image_digest=$(python resultes-docker-utils/push_docker_image_and_get_digest.py ghcr.io/spf-ost/resultes-server-api:latest)
          echo "image_digest=${image_digest}" >> "$GITHUB_ENV"
